name: " Feature"
description: "Nueva funcionalidad o mejora"
labels: ["feature"]
body:
  - type: dropdown
    id: area
    attributes:
      label: rea
      options:
        - API
        - Cliente
        - Ambos
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Prioridad
      options:
        -  Alta
        -  Media
        -  Baja
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descripci贸n
      description: "驴Qu茅 se quiere lograr?"
      placeholder: "Como usuario quiero..."
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Criterios de aceptaci贸n
      description: "驴C贸mo sabemos que est谩 completo?"
      placeholder: |
        - [ ] Endpoint creado y documentado
        - [ ] Pantalla en el cliente
        - [ ] Tests
    validations:
      required: true

  - type: textarea
    id: technical
    attributes:
      label: Notas t茅cnicas
      description: "Detalles de implementaci贸n, endpoints, esquemas, etc."
      placeholder: "Endpoint: POST /api/alerts ..."
    validations:
      required: false
